default: &default
  adapter: postgresql 
  encoding: unicode

development:
  <<: *default
  host: localhost
  database: myblogdevelopment
test:
  <<: *default
  host: localhost
  database: myblogtest

production:
  <<: *default
  database: myblogproduction